export const styles = {
  card: {
    background: "#fff",
    border: "0.5px solid #e5e7eb",
    borderRadius: 12,
    padding: "1.25rem",
    maxWidth: 420,
    fontFamily: "sans-serif",
    color: "#111",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 14,
  },
  courseLabel: {
    fontSize: 12,
    color: "#6b7280",
    margin: "0 0 4px",
  },
  courseName: {
    fontSize: 17,
    fontWeight: 500,
    margin: 0,
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    fontSize: 12,
    padding: "3px 10px",
    borderRadius: 8,
    background: "#eff6ff",
    color: "#1d4ed8",
    fontWeight: 500,
    whiteSpace: "nowrap",
  },
  timeBlock: {
    background: "#f9fafb",
    borderRadius: 8,
    padding: "10px 14px",
    marginBottom: 14,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
  },
  timeLabel: {
    fontSize: 11,
    color: "#9ca3af",
    margin: "0 0 2px",
    textAlign: "center",
  },
  timeValue: {
    fontSize: 22,
    fontWeight: 500,
    margin: 0,
    textAlign: "center",
  },
  arrow: {
    fontSize: 18,
    color: "#d1d5db",
  },
  row: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "8px 0",
    borderBottom: "0.5px solid #f3f4f6",
    fontSize: 14,
  },
  rowLast: {
    borderBottom: "none",
    paddingTop: 10,
  },
  rowLabel: {
    color: "#6b7280",
  },
  rowValue: {
    fontWeight: 500,
  },
  teacherRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: "50%",
    background: "#dcfce7",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 11,
    fontWeight: 500,
    color: "#15803d",
    flexShrink: 0,
  },
  teacherName: {
    fontSize: 13,
    fontWeight: 500,
  },
  activeDot: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    background: "#16a34a",
    display: "inline-block",
    marginRight: 5,
  },
  activeText: {
    display: "inline-flex",
    alignItems: "center",
    fontSize: 13,
    fontWeight: 500,
    color: "#16a34a",
  },
  idText: {
    fontSize: 11,
    color: "#9ca3af",
    fontFamily: "monospace",
  },
} as const;